Import("env")
from pathlib import Path
import gzip

# Configuration: Toggle compression on/off
ENABLE_COMPRESSION = True

src_dir = Path(env.subst("$PROJECT_SRC_DIR"))
out_dir = src_dir / "generated" / "html"
out_dir.mkdir(parents=True, exist_ok=True)

web_dir = src_dir / "web" / "server" / "html"

def compress_gzip(data: str) -> bytes:
    """Compress HTML string with gzip"""
    return gzip.compress(data.encode('utf-8'), compresslevel=9)

def escape_cpp_string(text: str) -> str:
    """Escape string for C++ string literal"""
    return (
        text.replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n\"\n\"")
    )

def bytes_to_c_array(data: bytes, var_name: str) -> str:
    """Convert bytes to C++ const char array format with PROGMEM"""
    hex_str = ', '.join(f'0x{b:02x}' for b in data)
    return f"const char {var_name}[] PROGMEM = {{\n    {hex_str}\n}};\nconst size_t {var_name}_len = {len(data)};"

def string_to_c_array(data: str, var_name: str) -> str:
    """Convert string to C++ const char array format with PROGMEM"""
    escaped = escape_cpp_string(data)
    return f'const char {var_name}[] PROGMEM = "{escaped}";\nconst size_t {var_name}_len = {len(data.encode("utf-8"))};\n'

# Collect all HTML data for single file output
all_arrays = []
total_original = 0
total_compressed = 0

for file in web_dir.rglob("*.html"):
    content = file.read_text(encoding="utf-8")
    var_name = file.stem
    total_original += len(content)

    if ENABLE_COMPRESSION:
        compressed = compress_gzip(content)
        c_array = bytes_to_c_array(compressed, var_name)
        total_compressed += len(compressed)
    else:
        c_array = string_to_c_array(content, var_name)
        total_compressed += len(content.encode("utf-8"))

    all_arrays.append(c_array)

# Generate single html.cpp with all data
cpp_content = (
    '/* AUTO-GENERATED FILE - DO NOT EDIT\n'
    ' * This file is automatically generated during build.\n'
    ' * Any manual changes will be overwritten.\n'
    ' */\n\n'
    '#include <pgmspace.h>\n'
    '#include "web/server/html.hpp"\n\n'
    "namespace Html {\n"
    f"    const bool isCompressed = {'true' if ENABLE_COMPRESSION else 'false'};\n\n"
    + "\n\n".join(all_arrays) + "\n"
    "}\n"
)

html_cpp_path = out_dir / "html.cpp"
html_cpp_path.write_text(cpp_content, encoding="utf-8")

if ENABLE_COMPRESSION:
    print(f"Generated: html.cpp (compression enabled: {total_original} -> {total_compressed} bytes)")
else:
    print(f"Generated: html.cpp ({total_original} bytes)")
