#include "httpclient.hpp"
#include <Arduino.h>
#include "system.hpp"
#include "config/config_pushapi.hpp"
#include "networking.hpp"


// MAy RAM usage before oldest datasets are deleted
const float MAX_RAM_USAGE = 80.0f;		// default: 80.0f [%]


HttpClient::HttpClient(const HttpAPI& api):
	m_api(api)
{

}

void HttpClient::init()
{
	m_timeLast = std::chrono::steady_clock::now();
	reload();
}

void HttpClient::reload()
{
	const Settings settings = loadSettings();

	bool enableWifi = (m_settings.enable && m_settings.disbaleWifi);

	if (validateSettings(settings))
	{

		m_settings = settings;
	}
	else
	{
		m_settings.enable = false;
		m_settings.serverHost = "";
		m_settings.serverLocationSmartMeter = "";
		m_settings.serverLocationSystem = "";
		m_settings.batchSize = 1;
		m_settings.disbaleWifi = false;
	}

	if (m_settings.enable)
	{
		if (m_settings.disbaleWifi)
			Networking::getInstance()->setEnableWifi(false);
	}
	else
	{
		m_mapDataSmartMeter.clear();
		m_mapDataSystem.clear();
	}

	if (m_clientSecure)
	{
		if (m_clientSecure->connected())
			m_clientSecure->stop();

		delete m_clientSecure;
		m_clientSecure = nullptr;
	}
}

void HttpClient::update()
{
	const auto timeNow = std::chrono::steady_clock::now();
	const auto timeDiff = (timeNow - m_timeLast);

	if (timeDiff < m_delayNext)
		return;

	m_batchCounter = std::max({ m_mapDataSmartMeter.size(), m_mapDataSystem.size() });

	Networking* const net = Networking::getInstance();

	if (m_batchCounter >= m_settings.batchSize)
	{
		if (!net->getEnableWifi())
			net->setEnableWifi(true);
	}

	if (!m_settings.enable
		|| m_settings.serverHost == ""
		|| m_batchCounter < m_settings.batchSize
		|| !net->getEnableWifi()
		|| !net->isWifiConnected())
	{
		m_delayNext = m_delayRetry;
		m_timeLast = timeNow;
		return;
	}

	// In order to avoid watchdog timeouts only one request is sent per update()
	// To avoid spamming the server, a small delay is set after every request
	// -> This delay can be configured, depending on if the request was successful or if there was an error

	// Upload system data first
	// -> System data is generated by the ESP and will always be available
	// -> Smartmeter data is only generated when data is received from the meter
	if (!handleResult(uploadSystem()))
	{
		m_timeLast = std::chrono::steady_clock::now();
		return;
	}

	if (!handleResult(uploadSmartMeter()))
	{
		m_timeLast = std::chrono::steady_clock::now();
		return;
	}

	// Disconnect after all data has been transmitted
	if (m_clientSecure)
	{
		if (m_clientSecure->connected())
			m_clientSecure->stop();

		delete m_clientSecure;
		m_clientSecure = nullptr;
	}

	// Only reset batch count when all data is transmitted
	m_batchCounter = 0;

	if (m_settings.disbaleWifi)
	{
		if (net->getEnableWifi())
			net->setEnableWifi(false);
	}

	m_timeLast = std::chrono::steady_clock::now();
}

HttpClient::Settings HttpClient::loadSettings()
{
	Config_PushAPI cfg;

	Settings settings;
	settings.enable = (cfg.getConfig(Config_PushAPI::ENABLE) == "true");
	settings.serverHost = cfg.getConfig(Config_PushAPI::SERVER_HOST);
	settings.serverLocationSmartMeter = cfg.getConfig(Config_PushAPI::SERVER_PATH_SMARTMETER);
	settings.serverLocationSystem = cfg.getConfig(Config_PushAPI::SERVER_PATH_SYSTEM);

	errno = 0;
	settings.batchSize = std::strtol(cfg.getConfig(Config_PushAPI::BATCH_SIZE).c_str(), nullptr, 10);
	settings.batchSize = (errno == 0 ? settings.batchSize : 0);

	settings.disbaleWifi = (cfg.getConfig(Config_PushAPI::DISABLE_WIFI) == "true");

	return settings;
}

void HttpClient::saveSettings(const Settings& settings)
{
	Config_PushAPI cfg;

	cfg.setConfig(Config_PushAPI::ENABLE, (settings.enable ? "true" : "false"));
	cfg.setConfig(Config_PushAPI::SERVER_HOST, settings.serverHost);
	cfg.setConfig(Config_PushAPI::SERVER_PATH_SMARTMETER, settings.serverLocationSmartMeter);
	cfg.setConfig(Config_PushAPI::SERVER_PATH_SYSTEM, settings.serverLocationSystem);
	cfg.setConfig(Config_PushAPI::BATCH_SIZE, std::to_string(settings.batchSize));
	cfg.setConfig(Config_PushAPI::DISABLE_WIFI, (settings.disbaleWifi ? "true" : "false"));
}

bool HttpClient::validateSettings(const Settings& settings)
{
	bool result = true;

	if (settings.enable)
	{
		if (settings.serverHost == "")
			result = false;

		else if (settings.serverLocationSmartMeter == "" && settings.serverLocationSystem == "")
			result = false;

		else if (settings.serverLocationSmartMeter != "" && !settings.serverLocationSmartMeter.starts_with("/"))
			result = false;

		else if (settings.serverLocationSystem != "" && !settings.serverLocationSystem.starts_with("/"))
			result = false;

		else if (settings.batchSize <= 0)
			result = false;
	}

	return result;
}

void HttpClient::callbackSmartmeter(const std::chrono::system_clock::time_point& tp, const DataSmartMeter& data)
{
	if (!m_settings.enable || m_settings.serverLocationSmartMeter == "")
		return;

	// Remove oldest data if memory gets full
	while (System::getRamHeapSizePercent() > MAX_RAM_USAGE && !m_mapDataSmartMeter.empty())
	{
		log_w("SM - Removing Oldest Data");

		const auto tpData = m_mapDataSmartMeter.cbegin()->first;
		m_mapDataSmartMeter.erase(tpData);

		if (m_mapDataSystem.contains(tpData))
			m_mapDataSystem.erase(tpData);
	}

	m_mapDataSmartMeter[tp] = data;
}

void HttpClient::callbackSystem(const std::chrono::system_clock::time_point& tp, const DataSystem& data)
{
	if (!m_settings.enable || m_settings.serverLocationSystem == "")
		return;

	// Remove oldest data if memory gets full
	while (System::getRamHeapSizePercent() > MAX_RAM_USAGE && !m_mapDataSystem.empty())
	{
		log_w("SYS - Removing Oldest Data");

		const auto tpData = m_mapDataSystem.cbegin()->first;
		m_mapDataSystem.erase(tpData);

		if (m_mapDataSmartMeter.contains(tpData))
			m_mapDataSmartMeter.erase(tpData);
	}

	m_mapDataSystem[tp] = data;
}

int8_t HttpClient::uploadSmartMeter()
{
	int8_t result = 0;

	if (m_settings.serverLocationSmartMeter == "")
		m_mapDataSmartMeter.clear();

	if (!m_mapDataSmartMeter.empty())
	{
		const auto& it = m_mapDataSmartMeter.cbegin();

		const std::string url = (m_settings.serverHost + m_settings.serverLocationSmartMeter);
		const ArduinoJson::JsonDocument doc = m_api.buildJsonSmartmeter(it->first, it->second);

		if (uploadJson(url, doc))
		{
			result = 1;
			m_mapDataSmartMeter.erase(it);
		}
		else
			result = -1;
	}

	return result;
}

int8_t HttpClient::uploadSystem()
{
	int8_t result = 0;

	if (m_settings.serverLocationSystem == "")
		m_mapDataSystem.clear();

	if (!m_mapDataSystem.empty())
	{
		const auto& it = m_mapDataSystem.cbegin();

		const std::string url = (m_settings.serverHost + m_settings.serverLocationSystem);
		const ArduinoJson::JsonDocument doc = m_api.buildJsonSystem(it->first, it->second);

		if (uploadJson(url, doc))
		{
			m_mapDataSystem.erase(it);
			result = 1;
		}
		else
			result = -1;
	}

	return result;
}

bool HttpClient::uploadJson(const std::string& url, const ArduinoJson::JsonDocument& doc)
{
	bool result = false;

	log_d("Sending HTTP Request to: %s", url.c_str());

	std::string strJson;
	ArduinoJson::serializeJson(doc, strJson);

	// Reuse connection whenever possible, but disconnect after all data has been transmitted
	const bool reuseConnection = (m_mapDataSmartMeter.size() + m_mapDataSystem.size() > 1);
	m_client.setReuse(reuseConnection);

	m_client.setConnectTimeout(m_timeoutConnect.count());
	m_client.setTimeout(m_timeoutReply.count());

	if (m_settings.serverHost.starts_with("https://"))
	{
		if (!m_clientSecure)
			m_clientSecure = new WiFiClientSecure();

		// Ignore self signed certificates
		m_clientSecure->setInsecure();

		// Handshake Timeout is set in seconds instead of milliseconds!
		m_clientSecure->setHandshakeTimeout(m_timeoutHandshake.count() / 1000);

		m_client.begin(*m_clientSecure, url.c_str());
	}
	else
		m_client.begin(url.c_str());

	m_client.addHeader("Content-Type", "application/json");

	const int httpResponseCode = m_client.POST(strJson.c_str());

	if (httpResponseCode > 0)
	{
		log_d("HTTP Response Code: %d", httpResponseCode);

		if (m_client.getSize() > 0)
		{
			const String payload = m_client.getString();
			log_d("Payload: %s", payload.c_str());
		}

		if (httpResponseCode >= 200 && httpResponseCode < 300)
			result = true;
	}
	else
	{
		log_e("Error sending HTTP Request: %d", httpResponseCode);
	}

	m_client.end();

	return result;
}

bool HttpClient::handleResult(int8_t resultUpload)
{
	bool result = true;

	if (resultUpload > 0)
	{
		m_delayNext = m_delayRequest;
		result = false;
	}
	else if (resultUpload < 0)
	{
		m_delayNext = m_delayRetry;
		result = false;
	}

	return result;
}
