#pragma once

#include <map>
#include <string>

enum DATA_POINT_SMARTMETER
{
	DP_ACTIVE_POWER_TOTAL,
	DP_ACTIVE_POWER_L1,
	DP_ACTIVE_POWER_L2,
	DP_ACTIVE_POWER_L3,

	DP_REACTIVE_POWER_TOTAL,
	DP_REACTIVE_POWER_L1,
	DP_REACTIVE_POWER_L2,
	DP_REACTIVE_POWER_L3,

	DP_APPARENT_POWER_TOTAL,
	DP_APPARENT_POWER_L1,
	DP_APPARENT_POWER_L2,
	DP_APPARENT_POWER_L3,

	DP_ACTIVE_ENERGY_IMPORT,
	DP_ACTIVE_ENERGY_EXPORT,

	DP_VOLTAGE_L1N,
	DP_VOLTAGE_L2N,
	DP_VOLTAGE_L3N,

	DP_VOLTAGE_L1L2,
	DP_VOLTAGE_L2L3,
	DP_VOLTAGE_L3L1,

	DP_CURRENT_L1,
	DP_CURRENT_L2,
	DP_CURRENT_L3,

	DP_POWER_FACTOR_TOTAL,
	DP_POWER_FACTOR_L1,
	DP_POWER_FACTOR_L2,
	DP_POWER_FACTOR_L3,

	DP_ANGLE_VOLTAGE_L1L2,
	DP_ANGLE_VOLTAGE_L2L3,
	DP_ANGLE_VOLTAGE_L3L1,

	DP_ANGLE_CURRENT_L1,
	DP_ANGLE_CURRENT_L2,
	DP_ANGLE_CURRENT_L3,

	DP_FREQUENCY,
};

enum DATA_POINT_SYSTEM
{
	DP_MCU_USAGE,
	DP_WIFI_RSSI,
	DP_TEMPERATURE,
};

const std::map<DATA_POINT_SMARTMETER, std::string> gc_mapDataPointInfoSmartmeter =
{
	{ DP_ACTIVE_POWER_TOTAL,      "ACT_POW_TOT" },
	{ DP_ACTIVE_POWER_L1,         "ACT_POW_L1" },
	{ DP_ACTIVE_POWER_L2,         "ACT_POW_L2" },
	{ DP_ACTIVE_POWER_L3,         "ACT_POW_L3" },

	{ DP_REACTIVE_POWER_TOTAL,    "REACT_POW_TOT" },
	{ DP_REACTIVE_POWER_L1,       "REACT_POW_L1" },
	{ DP_REACTIVE_POWER_L2,       "REACT_POW_L2" },
	{ DP_REACTIVE_POWER_L3,       "REACT_POW_L3" },

	{ DP_APPARENT_POWER_TOTAL,    "APP_POW_TOT" },
	{ DP_APPARENT_POWER_L1,       "APP_POW_L1" },
	{ DP_APPARENT_POWER_L2,       "APP_POW_L2" },
	{ DP_APPARENT_POWER_L3,       "APP_POW_L3" },

	{ DP_ACTIVE_ENERGY_IMPORT,    "ACT_ENG_IMP" },
	{ DP_ACTIVE_ENERGY_EXPORT,    "ACT_ENG_EXP" },

	{ DP_VOLTAGE_L1N,             "U_L1N" },
	{ DP_VOLTAGE_L2N,             "U_L2N" },
	{ DP_VOLTAGE_L3N,             "U_L3N" },

	{ DP_VOLTAGE_L1L2,            "U_L1L2" },
	{ DP_VOLTAGE_L2L3,            "U_L2L3" },
	{ DP_VOLTAGE_L3L1,            "U_L3L1" },

	{ DP_CURRENT_L1,              "I_L1" },
	{ DP_CURRENT_L2,              "I_L2" },
	{ DP_CURRENT_L3,              "I_L3" },

	{ DP_POWER_FACTOR_TOTAL,      "PF_TOT" },
	{ DP_POWER_FACTOR_L1,         "PF_L1" },
	{ DP_POWER_FACTOR_L2,         "PF_L2" },
	{ DP_POWER_FACTOR_L3,         "PF_L3" },

	{ DP_ANGLE_VOLTAGE_L1L2,      "ANG_U_L1L2" },
	{ DP_ANGLE_VOLTAGE_L2L3,      "ANG_U_L2L3" },
	{ DP_ANGLE_VOLTAGE_L3L1,      "ANG_U_L3L1" },

	{ DP_ANGLE_CURRENT_L1,        "ANG_I_L1" },
	{ DP_ANGLE_CURRENT_L2,        "ANG_I_L2" },
	{ DP_ANGLE_CURRENT_L3,        "ANG_I_L3" },

	{ DP_FREQUENCY,               "FREQ" },
};

const std::map<DATA_POINT_SYSTEM, std::string> gc_mapDataPointInfoSystem =
{
	{ DP_MCU_USAGE,               "MCU_USAGE" },
	{ DP_WIFI_RSSI,               "WIFI_RSSI" },
	{ DP_TEMPERATURE,             "TEMP" },
};
